tasks/urls.py
from django.urls import path
from tasks import views

app_name = "tasks"

urlpatterns = [
    path("", views.index, name="index"),
    path("list/", views.TaskListView.as_view(), name="list"),
    path("list/c/<slug:cat_slug>", views.tasks_by_cat, name="list_by_cat"),
    path("details/<int:pk>", views.TaskDetailsView.as_view(), name="details"),
    path("cached_time/", views.get_cashed_time, name="cached_time"),
]

todoapp/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve
from django.conf.urls.static import static

urlpatterns = [
    path('', include('tasks.urls', namespace="tasks")),
    path('admin/', admin.site.urls),
    re_path(r'^static/(?P<path>.*)$', serve,
            {'document_root': settings.STATIC_ROOT}),
]

# if not settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         path("__debug__/", include(debug_toolbar.urls))
#     ] + urlpatterns

tasks/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

class Category(models.Model):
    slug = models.CharField(max_length=128)
    name = models.CharField(max_length=256)
    count = models.PositiveIntegerField(default=0)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return f'{self.name} ({self.slug})'

class Priority(models.Model):

    PRIORITY_CHOICES = [
        ("High Priority", "Высокий приоритет"),
        ("Medium Priority", "Средний приоритет"),
        ("Low Priority", "Низкий приоритет"),
    ]

    name = models.CharField(max_length=128,
        choices=PRIORITY_CHOICES, default="Medium Priority"
        )
    count = models.PositiveIntegerField(default=0)

    class Meta:
        verbose_name = 'Приоритет'
        verbose_name_plural = 'Приоритеты'

    def __str__(self):
        return self.name

class TodoItem(models.Model):
    description = models.TextField("Описание")
    is_completed = models.BooleanField("Выполнено", default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name=u'Владелец',
        )
    category = models.ManyToManyField(
    	Category,
    	verbose_name=u'Категория',
    	blank=True
    	)
    priority = models.ForeignKey(
        Priority,
        on_delete=models.CASCADE,
        verbose_name=u'Приоритет',
        blank=True
        )

    class Meta:
        verbose_name = 'Задачу'
        verbose_name_plural = 'Задачи'

    def __str__(self):
        return self.description.lower()

    def get_absolute_url(self):
        return reverse("tasks:details", args=[self.pk])

tasks/views.py
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from tasks.models import TodoItem, Category, Priority
from django.views.generic.base import View
from datetime import datetime
from django.core.cache import cache

def index(request):
    categories = Category.objects.all()
    priorities = Priority.objects.all()
    return render(request, "index.html", {"categories": categories, "priorities": priorities,})

def tasks_by_cat(request, cat_slug=None):
    user = request.user
    tasks = TodoItem.objects.filter(owner=user).all()
    cat = None
    if cat_slug:
        cat = get_object_or_404(Category, slug=cat_slug)
        tasks = tasks.filter(category__in=[cat])
    categories = Category.objects.all()
    return render(
        request,
        "list_by_cat.html",
        {"category": cat, "tasks": tasks, "categories": categories},
    )

class TaskListView(ListView):
    model = TodoItem
    context_object_name = "tasks"
    template_name = "list.html"

class TaskDetailsView(DetailView):
    model = TodoItem
    template_name = "details.html"

def get_cashed_time(request):
    timenow = datetime.now().strftime("%d-%m-%Y / %H:%M:%S") 
    if not cache.get('cached_time'):
        cache.set('cached_time', timenow, 300)
    return render(request, "cached_time.html", {'current_time': timenow,
                                                'cached_time': cache.get('cached_time'), })

templates/base.html
6<html>
<head>
    <title>{% block title %}PWS Todo example app{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <script src="http://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    {% block extra_head %}{% endblock %}
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="side_bar col">
                {% block side_bar %}
                {% if user.is_authenticated %}
                <p class="h6">Приветствую, <span class="text-secondary">{{ user.username }}</span>!</p>
                <div class="d-block">
                    <i class="fas fa-clipboard-list"></i>&nbsp;<a href="{% url 'tasks:index' %}">Категории задач и приоритеты исполнения</a>
                </div>
                <div class="d-block">
                    <i class="fas fa-clipboard-list"></i>&nbsp;<a href="{% url 'tasks:list' %}">Список задач</a>
                </div>
                <div class="d-block">
                    <i class="fas fa-clipboard-list"></i>&nbsp;<a href="{% url 'tasks:cached_time' %}">Кэширование времени на 5 минут</a>
                </div>
                {% endif %}
                    <i class="fas fa-cog"></i>&nbsp;<a href="{% url 'admin:index' %}">Админка</a>
                {% endblock %}
            </div>
            <div class="main_content col-8">
                {% block main_content %}{% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

templates/cached_time.html
{% extends "base.html" %}
{% load static %}
{% block title %}Кэшированное Время{% endblock %}
{% block main_content %}
	<div class="mt-3">
		<h1 class="text-primary my-3">Текущее время</h1>
		<h4 class="text-success">
			{{ current_time }}
		</h4>
	</div>
	<div class="mt-3">
		<h1 class="text-primary my-3">Кешированное время</h1>
		<h4 class="text-danger">
			{{ cached_time }}
		</h4>
	</div>
{% endblock %}

templates/details.html
{% extends "base.html" %}
{% block title %}Поручение {{ object.id }}{% endblock %}

{% block main_content %}

    <h1 class="text-primary my-3">Поручение</h1>
    <p><b>Описание</b>: <span class="text-danger">{{ object }}</span></p>
    <ul>
        <li>
            {{ object.is_completed|yesno:"Выполнено,Не выполнено" }}
        </li>
        <li><i class="far fa-calendar-alt"></i>&nbsp;Создано: {{ object.created|date:"Y-b-d H:i" }}</li>
        <li><i class="far fa-clock"></i>&nbsp;Последнее изменение: {{ object.updated }}</li>
    </ul>
    <i class="fas fa-clipboard-list"></i>&nbsp;<a href="{% url 'tasks:list' %}">Назад к списку</a>

{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}Информация по категориям{% endblock %}

{% block main_content %}

	<h1 class="text-primary my-3">Категории и число задач</h1>
	<ul class="list-unstyled">
	{% for cat in categories %}
		{% if user.is_authenticated %}
		<li><a href="{% url 'tasks:list_by_cat' cat.slug %}"><span class="badge badge-info">{{ cat.name }} : {{ cat.count }}</span></a></li>
		{% else %}
		<li><span class="badge badge-info">{{ cat.name }} : {{ cat.count }}</span></li>
		{% endif %}
		{% empty %}
		<li>Список задач по категориям пуст. Попробуйте добавить их из админки</li>
		{% endfor %}
	</ul>
	<h1 class="text-primary my-3">Приоритеты и число задач</h1>
	<ul class="list-unstyled">
		{% for prior in priorities %}
		{% if prior.name == 'High Priority' %}
		<li><span class="badge badge-danger">{{ prior.name }} : {{ prior.count }}</span></li>
		{% elif prior.name == 'Medium Priority' %}
		<li><span class="badge badge-warning">{{ prior.name }} : {{ prior.count }}</span></li>
		{% elif prior.name == 'Low Priority' %}
		<li><span class="badge badge-success">{{ prior.name }} : {{ prior.count }}</span></li>
		{% endif %}
		{% empty %}
		<li>Список задач по приоритетам пуст. Попробуйте добавить их из админки</li>
		{% endfor %}
	</ul>

{% endblock %}

templates/list.html
{% extends "base.html" %}
{% load static %}
{% block title %}Список поручений{% endblock %}
{% block main_content %}

    <h1 class="text-primary mt-3 mb-5">Текущие поручения&nbsp;</h1>
    <ul id="todo-list">
    {% for task in tasks %}
    <li class="completed list-unstyled">
        {% if task.is_completed %}
        <input class='checkbox' data-uid={{ task.id }} type='checkbox' disabled='disabled' checked='checked'/>
        {% endif %}
        <a href="{% url 'tasks:details' task.id %}">
        {% if task.priority.name == 'High Priority' %}
        <span class="badge badge-pill badge-danger">{{ task.description }} : High Priority</span>
        {% elif task.priority.name == 'Medium Priority' %}
        <span class="badge badge-pill badge-warning">{{ task.description }} : Medium Priority</span>
        {% elif task.priority.name == 'Low Priority' %}
        <span class="badge badge-pill badge-success">{{ task.description }} : Low Priority</span>
        {% endif %}
        </a>
        <hr/>
        </li>
    {% endfor %}
    </ul>
{% endblock %}

templates/list_by_cat.html
{% extends "base.html" %}
{% load static %}

{% block title %}Поручения на день{% endblock %}

{% block main_content %}

    {% if category %}
    <h1 class="text-primary text-justify-center my-3"> Поручения категории "<span class="text-success">{{ category.name }}</span>"</h1>
    {% else %}
    <h1 class="text-primary my-3">Все текущие поручения</h1>
    {% endif %}
    {% for cat in categories %}
    {% if forloop.first %}
    <ul class="list-inline">
      <li class="list-inline-item">Все категории:</li>
    {% endif %}
        <li class="list-inline-item">
            <a href="{% url 'tasks:list_by_cat' cat.slug %}">
            {% if category == cat %}
            <span class="badge badge-success">{{ cat.name }}</span>
            {% else %}
            <span class="badge badge-info">{{ cat.name }}</span>
            {% endif %}
            </a>
        </li>
    {% if forloop.last %}</ul>{% endif %}
    {% endfor %}
    <hr/>

    <ul id="todo-list">
    {% for task in tasks %}
        <li class="completed list-unstyled">
            {% if task.is_completed %}
            <input class='checkbox' data-uid={{ task.id }} type='checkbox' disabled='disabled' checked='checked'/>
            {% endif %}
            <a href="{% url 'tasks:details' task.id %}">
            {% if task.priority.name == 'High Priority' %}
            <span class="badge badge-pill badge-danger">{{ task }} : High Priority</span>
            {% elif task.priority.name == 'Medium Priority' %}
            <span class="badge badge-pill badge-warning">{{ task }} : Medium Priority</span>
            {% elif task.priority.name == 'Low Priority' %}
            <span class="badge badge-pill badge-success">{{ task }} : Low Priority</span>
            {% endif %}
            </a>
            <hr/>
        </li>
    {% endfor %}
    </ul>

{% endblock %}